### PR TITLE
Palindrome Checker

### PR DESCRIPTION
**Pull request by faridafaqiri**
This repository is about Palindrome checker which I did in this repository:
- I created index.html file which have these things inside it:
   - added head tag inside of head tag added link, title, meta tag.
   - added body tag inside it add h1, div, label, input, button, p.
   - also added script element for link to script.js with html file.
- I created syles.css file which I designed:
   - I styled body tag, button, input and div with calling the class name.
- I create JavaScript file in this file I did:
   - assign some key word for define a variable used document.getElementById method.
   - used if and else condition for checking a condition.
- Setup linters configuration.

### CODE REVIEW

**Comment by faridafaqiri** [comment]
@Fikrat2002
hi!
I'm witting for your feedback.

**Comment by Fikrat2002** [comment]
Hi @far_faqiri 🙋‍♀,

Great job! 💯 You've nailed all the project requirements👏Your feature is complete! Congratulations!!! 🎊🏆

Status: Approved ✅
Note: A tiny change is required📍
Everything looks perfect. Just  add a deployment link in your README file then merge your project 🏆🎊👏

Highlights 🌞
🏆 Successfully implemented a great design
✅ Created a professional repository with your project name
✅ Passed FreeCodeCamp requirements for the project 
✅ Used Gitflow correctly by creating a development branch, setting it as default, and making commits on your feature branch
✅ Wrote meaningful commit messages
✅ Set up appropriate linter configurations based on your project's language
✅ No linter errors!
✅ Followed the task and used command-line commits
✅ Submitted a pull request from your feature branch to the development branch and shared the link for review
✅ Provided a clear and detailed description of your work in the PR
✅ Maintained clean code
✅ Created a professional README.md file in your repository
✅ The project is responsive 
❌ Created live deployment link

**Comment by faridafaqiri** [comment]
@Fikrat2002 
thank you for your available feedback I added deployment link in readme file.

**Comment by faridafaqiri** [comment]
@ahzamir 
Hi dear mentor!
after my partner feedback I'm now waiting for your feedback.

**Review by ahzamir — APPROVED** [review]
### Hi @faridafaqiri 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image


# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Palindrome Checker project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
